name: Bump version
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/tag_version.yml'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dragosd2000/versioner:latest
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        run: |
          versioner
