name: Bump version
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/tag_version.yml'

defaults:
  run:
    shell: bash
    working-directory: repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
#          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        run: |
          docker run -v $(pwd):/repo --rm dragosd2000/versioner
