name: Bump version
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/tag_version.yml'

jobs:
  build:
    runs-on: dragosd2000/versioner
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        run: |
          - versioner
